# Generated by Django 6.0 on 2026-02-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('accountNumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accountHolder', models.CharField(max_length=40)),
                ('balance', models.FloatField(default=0)),
                ('pin', models.IntegerField()),
                ('bankName', models.CharField(max_length=15)),
            ],
        ),
    ]
