# Generated by Django 6.0 on 2026-02-05 09:43

import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('accountNumber', models.BigAutoField(default=myApp.models.generate_account_number, editable=False, primary_key=True, serialize=False)),
                ('accountHolder', models.CharField(max_length=40)),
                ('balance', models.FloatField(default=0)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('bankName', models.CharField(max_length=15)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
