# Generated by Django 6.0 on 2026-02-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_bankdetails_mobile_alter_bankdetails_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='mobile',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
