# Generated by Django 6.0 on 2026-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_bankdetails_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='accountNumber',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
