# Generated by Django 6.0 on 2026-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_bankdetails_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
